# Generated by Django 4.0 on 2021-12-31 11:08

from django.db import migrations, models
import picklefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('args', picklefield.fields.PickledObjectField(editable=False)),
            ],
        ),
    ]
